### ISSUE TITLE
weekly Q7b condition is broken

### ISSUE THREAD

**Issue by m-delfino** [influenzanet/common-study-definition#14]
`codes.other` should be `codes.plan` here:

https://github.com/influenzanet/common-study-definition/blob/cddee88208315fe16ed79e3bab2741d0d4702300/src/studies/common/questionPools/weeklyQuestions.ts#L1704

**Comment by cturbelin** [comment]
Fixed b6b3fa5b31282d923c537b9b167d3620c2073541
