### ISSUE TITLE
weekly Qcov18 condition is wrong

### ISSUE THREAD

**Issue by m-delfino** [influenzanet/common-study-definition#15]
`responseHasOnlyKeysOtherThan` should be `responseHasKeysAny`

https://github.com/influenzanet/common-study-definition/blob/cddee88208315fe16ed79e3bab2741d0d4702300/src/studies/common/questionPools/weeklyQuestions.ts#L1863

**Comment by cturbelin** [comment]
Fixed in 2aaf4f203963f80861f436e0c125cc4511da0c25
