### ISSUE TITLE
weekly Qcov18 has wrong hint

### ISSUE THREAD

**Issue by m-delfino** [influenzanet/common-study-definition#16]
since this is a single choice question

https://github.com/influenzanet/common-study-definition/blob/560fc30f54ea039eec920d6f292b91c61ff64cb6/src/studies/common/questionPools/weeklyQuestions.ts#L1870

should not be there

**Comment by cturbelin** [comment]
Fixed in 6dee9772d8d64c81f8c1984a2bf9886cbb5fa051
