### ISSUE TITLE
wrong study rule for hasOnGoingSymptoms flag

### ISSUE THREAD

**Issue by m-delfino** [influenzanet/common-study-definition#18]
This study rule is wrong:

https://github.com/influenzanet/common-study-definition/blob/ae0ed0fd230e93a8fccfeda968e6efe8a02abd4c/src/studies/common/rules.ts#L58

should instead be checking weekly.Q4 == 2:

https://github.com/influenzanet/common-study-definition/blob/ae0ed0fd230e93a8fccfeda968e6efe8a02abd4c/src/studies/common/questionPools/weeklyQuestions.ts#L583

so we also need to export a different key here:

https://github.com/influenzanet/common-study-definition/blob/ae0ed0fd230e93a8fccfeda968e6efe8a02abd4c/src/studies/common/surveys/weekly.ts#L156

**Comment by cturbelin** [comment]
Fixed in 8394166ed8577f527c483ccd925e5838ffcf78d5
