### ISSUE TITLE
vaccination Q10d wrong influenza season

### ISSUE THREAD

**Issue by md-isi** [influenzanet/common-study-definition#21]
This is a question for the current influenza season, beware of the misleading text, as of today should be 2022/2023 but it's still 2020/2021:

https://github.com/influenzanet/common-study-definition/blob/8394166ed8577f527c483ccd925e5838ffcf78d5/src/studies/common/questionPools/vaccinationQuestions.ts#L431

**Comment by cturbelin** [comment]
Fixed in e301d6f563a1f068b5ca0babd539bd324b10d619, reference text is now generic
