### ISSUE TITLE
inputDate: use description instead of content

### ISSUE THREAD

**Issue by md-isi** [influenzanet/common-study-definition#5]
using `content` for the input field description produces this output:

![content](https://user-images.githubusercontent.com/103664369/170303154-13230a71-a277-4439-9a6b-a154cd1e0479.png)

using `description` produces this content instead:

![description](https://user-images.githubusercontent.com/103664369/170303457-1cbf42b6-906a-4e7f-b38e-dae46620539f.png)

which might be preferrable

**Comment by cturbelin** [comment]
Done in 862b25ea8cfa1ca186c40f0a838cffaffe21ef03
